[package]
name = "unarm-c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
unarm = { version = "1.9.1", default-features = false, features = [
	"arm",
	"thumb",
	"v5te",
	"v4t",
] }
